# Generated by Django 4.1.5 on 2023-03-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neorecipe_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='recipebook',
            name='isbn',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
