# Generated by Django 4.2 on 2023-04-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neorecipe_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neorecipeuser',
            name='userprefs',
            field=models.TextField(default=''),
        ),
    ]
