# Generated by Django 4.2 on 2023-04-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neorecipe_api', '0002_recommendedrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='neorecipe_api.bookcontributor'),
        ),
    ]
