# Generated by Django 4.2 on 2023-04-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neorecipe_api', '0004_recipebook_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipebook',
            name='isbn',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
