# Generated by Django 4.2 on 2023-04-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neorecipe_api', '0005_alter_recipebook_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='neorecipeuser',
            name='pantry_items',
            field=models.ManyToManyField(to='neorecipe_api.recipeingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='neorecipe_api.recipe'),
        ),
    ]
